export const pageCacheKey = (id: string) => `pagecache#${id}`;
export const usersKey = (userId: string) => `users#${userId}`;
export const sessionsKey = (userId: string) => `sessions#${userId}`;
export const itemsKey = (itemId: string) => `items#${itemId}`;
export const usernamesUniqueKey = () => 'usernames:unique';
export const userLikesKey = (userId: string) => `users:likes#${userId}`;
export const usernamesKey = () => 'usernames';
export const itemsByViewsKey = () => `items:views`;
export const itemsViewsKey = (itemId: string) => `items:views#${itemId}`;
export const itemsByEndingAtKey = () => 'items:endingAt';
export const bidHistoryKey = (itemId: string) => `history#${itemId}`;
export const itemsByPriceKey = () => `items:price`;
export const itemsIndexKey = () => `idx:items`;
